name: Prepare pages for Hugo
on:
  schedule:
    - cron: '30 6,10,12,14,16,18 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  java:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DJB_GH_PAGES }}
          ref: gh-pages-staging
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots package
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages-staging
          commit_message: New blogs added
          file_pattern: 'hugo/** data/**'

